targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: cl_ecommerce_graphql|lib/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: cl_ecommerce_graphql|lib/schema.graphql
