name: Create Release Branch
run-name: release new version 🚀
on:
  release:
    types: [published]
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF}" >> $GITHUB_ENV
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: "release/${{ env.RELEASE_VERSION }}"
      - uses: flutter-actions/setup-flutter@v2
      - run: rm -f .gitignore
      - run: flutter pub get
      - run: flutter run build_runner build --delete-conflicting-outputs
      - name: Commit Push
        uses: actions-js/push@master
        with:
          github_token: ${{ github.token }}
          branch: "release/${{ env.RELEASE_VERSION }}"
  


  

