name: Create Release Branch
run-name: release new version 🚀
on:
  release:
    types: [published]
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF}" >> $GITHUB_ENV

  create_branch:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: "release/${{ env.RELEASE_VERSION }}"

  setup_gen_files:
    name: Setup Generate Files
     runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1
      - run: rm .gitignore
      - run: dart pub get
      - run: dart run build_runner build --delete-conflicting-outputs
  
  commit_push:
    name: Commit Push
     runs-on: ubuntu-latest
    steps:
      - name: Commit Push
        uses: actions-js/push@master
        with:
          github_token: ${{ github.token }}
          branch: "release/${{ env.RELEASE_VERSION }}"
  


  

